version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3002:80'  # You can use 80 in production
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5004:5000'   # 5000 is internal, 5003 exposed outside
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
